In [14]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set()

from sklearn.linear_model import LinearRegression

In [4]:
data = pd.read_csv('Multiple+linear+regression2.csv')

In [5]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [7]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [8]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [15]:
reg_with_pvalues = LinearRegression()
reg_with_pvalues.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
from sklearn.feature_selection import f_regression

In [20]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [21]:
p_values = f_regression(x,y)[1]

In [22]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [24]:
p_values.round(3)

array([0.   , 0.676])

In [25]:
reg_summary = pd.DataFrame(data = x.columns.values, columns =['features'])
reg_summary

features
0         SAT
1  Rand 1,2,3